//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductAssignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTB
    {
        public int ID { get; set; }
        public string ProductName { get; set; }
        public int CategoryID { get; set; }
        public int UnitID { get; set; }
        public int Price { get; set; }
    
        public virtual CategoryTB CategoryTB { get; set; }
        public virtual UnitTB UnitTB { get; set; }
    }
}
