//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductAssignment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProductDBEntities3 : DbContext
    {
        public ProductDBEntities3()
            : base("name=ProductDBEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryTB> CategoryTBs { get; set; }
        public virtual DbSet<ProductTB> ProductTBs { get; set; }
        public virtual DbSet<UnitTB> UnitTBs { get; set; }
    }
}
